
package webAuction;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegistrationWebService", targetNamespace = "http://web.webAuction/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RegistrationWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns webAuction.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://web.webAuction/", className = "webAuction.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://web.webAuction/", className = "webAuction.RegisterResponse")
    @Action(input = "http://web.webAuction/RegistrationWebService/registerRequest", output = "http://web.webAuction/RegistrationWebService/registerResponse")
    public User register(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webAuction.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://web.webAuction/", className = "webAuction.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://web.webAuction/", className = "webAuction.GetUserResponse")
    @Action(input = "http://web.webAuction/RegistrationWebService/getUserRequest", output = "http://web.webAuction/RegistrationWebService/getUserResponse")
    public User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
