
package webAuction;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegistrationWebServiceService", targetNamespace = "http://web.webAuction/", wsdlLocation = "http://localhost:5000/WebAuction/Registration?wsdl")
public class RegistrationWebServiceService
    extends Service
{

    private final static URL REGISTRATIONWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException REGISTRATIONWEBSERVICESERVICE_EXCEPTION;
    private final static QName REGISTRATIONWEBSERVICESERVICE_QNAME = new QName("http://web.webAuction/", "RegistrationWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5000/WebAuction/Registration?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTRATIONWEBSERVICESERVICE_WSDL_LOCATION = url;
        REGISTRATIONWEBSERVICESERVICE_EXCEPTION = e;
    }

    public RegistrationWebServiceService() {
        super(__getWsdlLocation(), REGISTRATIONWEBSERVICESERVICE_QNAME);
    }

    public RegistrationWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTRATIONWEBSERVICESERVICE_QNAME, features);
    }

    public RegistrationWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, REGISTRATIONWEBSERVICESERVICE_QNAME);
    }

    public RegistrationWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTRATIONWEBSERVICESERVICE_QNAME, features);
    }

    public RegistrationWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrationWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegistrationWebService
     */
    @WebEndpoint(name = "RegistrationWebServicePort")
    public RegistrationWebService getRegistrationWebServicePort() {
        return super.getPort(new QName("http://web.webAuction/", "RegistrationWebServicePort"), RegistrationWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrationWebService
     */
    @WebEndpoint(name = "RegistrationWebServicePort")
    public RegistrationWebService getRegistrationWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://web.webAuction/", "RegistrationWebServicePort"), RegistrationWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTRATIONWEBSERVICESERVICE_EXCEPTION!= null) {
            throw REGISTRATIONWEBSERVICESERVICE_EXCEPTION;
        }
        return REGISTRATIONWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
